[build]
languages = "python"

[phases.build]
cmds = [
  "python -m pip install -r requirements.txt",
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn girl_power_club.wsgi --bind 0.0.0.0:$PORT"
